### ISSUE TITLE
Crash, see description.

### ISSUE THREAD

**Issue by eidheim** [cppit/libclangmm#13]
Assertion failed: (Val && "isa<> used on a null pointer"), function doit, file /tmp/llvm20150628-7874-1qnjbb2/llvm-3.6.1.src/include/llvm/Support/Casting.h, line 95.

**Comment by zalox** [comment]
When does it occur?

**Comment by eidheim** [comment]
Happened once while I wrote code, but was unable to reproduce the crash. Hopefully we'll figure out which pointer it is.

**Comment by eidheim** [comment]
Seems like the problem lies in Cursor.cc. Did a `grep isa *.cpp` in `clang/tools/libclang` after cloning `https://github.com/llvm-mirror/clang.git`.

**Comment by eidheim** [comment]
Or.. I'm not sure. Might be jucipp's source.cc that try read from libclang's translationunit or cursors while they are being processed. Might be an exception there I have not thought of yet:)

**Comment by eidheim** [comment]
The problem was in source.cc, I had added a reference that sometimes was empty. Committing fix Tomorrow.

**Comment by eidheim** [comment]
Fixed in latest commit to jucipp.
