### ISSUE TITLE
lowercase issue for LIBCLANGMM_BUILD_TESTS

### ISSUE THREAD

**Issue by dfleury2** [cppit/libclangmm#28]
Hi,
in the CmakeLists.txt file, LIBCLANGMM_BUILD_TESTS is incorrectly spelled in lowercase (line 14)

**Comment by eidheim** [comment]
Thank you, I also updated the README.md. We should really move away from the boost test framework and create simpler tests instead, as done in juCi++. The tests should also utilise boost::filesystem so that `make test` would work.
