### ISSUE TITLE
No rule to make target

### ISSUE THREAD

**Issue by mynameisbreak** [cppit/libclangmm#31]
make[2]: *** No rule to make target '/usr/local/lib/libclang.so', needed by 'lib/libclangmm.so'。 stop。
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/clangmm.dir/all' failed
make[1]: *** [src/CMakeFiles/clangmm.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by eidheim** [comment]
Thank you, I messed up a rebase it seems. Should be fixed now.
