### ISSUE TITLE
Move installation guide to docs/install.md

### ISSUE THREAD

**Issue by zalox** [cppit/libclangmm#7]
Please create docs/install.md in this project
- create /docs/install.md
- move install instructions to that file (from readme.md)
- link to this file in readme.md in both juci++ and libclanmm project

**Comment by oyvang** [comment]
Which dependencies are required? only libclang? I am not sure but i think i remember to install a boost library as well, but i can not find any in the CMakeLists.

**Comment by zalox** [comment]
boost log is required at least
